export const lang = {
    Afrikaans: "af",
    Albanian: "sq",
    Amharic: "am",
    Arabic: "ar",
    Armenian: "hy",
    Azerbaijani: "az",
    Basque: "eu",
    Belarusian: "be",
    Bengali: "bn",
    Bosnian: "bs",
    Bulgarian: "bg",
    Catalan: "ca",
    ChineseSimplified: "zh-CN",
    ru: "russian",
    de: "german",
    en: "english",
    es: "spain",
    ja: "japanese",
    fr: "french",
    zh: "chinese",
    it: "italian",
    ar: "arabic"
}